#!/bin/bash

# Color codes
GREEN="\033[0;32m"
BLUE="\033[1;34m"
NC="\033[0m"  # No Color

pacman_installs=(
  waybar
  wlsunset
  dconf-editor
  papirus-icon-theme
  swaync
  rofi-wayland
  rofi-calc
  rofi-emoji
  cliphist
  wl-clipboard
  dart-sass
  matugen
  jq
  bc
)

yay_aur_installs=(
  1password
  hyprlock
  quickshell-git
  ttf-material-symbols-variable-git
)

is_installed() {
    pacman -Q "$1" &>/dev/null
}


# install pacman packages
for pkg in "${pacman_installs[@]}"; do
  if is_installed "$pkg"; then
    echo -e "${GREEN}$pkg is already installed${NC} "
  else
    echo -e "${BLUE}Installing $pkg via pacman...${NC}"
    sudo pacman -S "$pkg"
    # sudo pacman -S --noconfirm "$pkg"
  fi
done


# Install AUR packages
for pkg in "${yay_aur_installs[@]}"; do
  if is_installed "$pkg"; then
    echo -e "${GREEN}$pkg is already installed${NC}"
  else
    echo -e "${BLUE}Installing $pkg via yay...${NC}"
    yay -S "$pkg"
    # yay -S --noconfirm "$pkg"
  fi
done








